name: "Setup XenServer SDK"
description: "Downloads and extracts XenServer SDK"
inputs:
  XENSERVER_SDK_URL:
    description: "The URL of the XenServer SDK"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: extract xensdk version
      id: extract-xensdk-version
      shell: bash
      run: |
        python - <<EOF
        import requests
        import re
        from bs4 import BeautifulSoup

        response = requests.get('https://www.xenserver.com/downloads')
        soup = BeautifulSoup(response.text, 'html.parser')

        pattern = re.compile(r'Software Development Kit \(SDK\) (\d+\.\d+\.\d+)')

        for text in soup.stripped_strings:
            match = pattern.search(text)
            if match:
                version = match.group(1)
                sdk_url = f'https://downloads.xenserver.com/sdk/{version}/XenServer-SDK-{version}.zip'
                env.GITHUB_OUTPUT = f'XENSERVER_SDK_URL={sdk_url}'
        EOF

    - name: Download and extract SDK
      shell: bash
      run: |
        url=${{ inputs.XENSERVER_SDK_URL }}
        if [ -z "$url" ]; then
          url=${{ steps.extract-xensdk-version.output.XENSERVER_SDK_URL }}
        fi
        curl -L $url -o xenserver-sdk.zip
        unzip -d goSDK xenserver-sdk.zip
        rm -rf XenServer-SDK* xenserver-sdk.zip
